# Generated by Django 5.0.7 on 2024-10-03 06:06

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='description',
            new_name='details_of_request',
        ),
        migrations.AddField(
            model_name='request',
            name='basis_of_request',
            field=models.CharField(default='Not provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 3, 6, 3, 59, 688530, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='requested_date_of_payment',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='type_of_vendor',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='vendor_code',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='vendor_name',
            field=models.CharField(default='Unnamed Vendor', max_length=255),
            preserve_default=False,
        ),
    ]
