# Generated by Django 5.0.7 on 2024-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_rename_description_request_details_of_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
