# Generated by Django 5.0.6 on 2024-10-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_vendor_branch_vendor_type_of_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_account_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
