# Generated by Django 5.0.6 on 2024-10-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0007_request_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
