# Generated by Django 5.0.7 on 2024-10-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0008_request_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='manager_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
