# Generated by Django 5.0.6 on 2024-10-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0009_request_manager_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type_of_vendor',
            field=models.CharField(choices=[('existing_vendor', 'Existing Vendor'), ('new_vendor', 'New Vendor')], max_length=50),
        ),
    ]
