# Generated by Django 5.1.2 on 2024-10-18 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0010_alter_request_type_of_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_app.request'),
        ),
    ]
