# Generated by Django 5.1.2 on 2024-10-18 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0012_rename_created_at_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='added_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['Finance', 'Admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
