# Generated by Django 5.1.2 on 2024-10-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0016_message_receiver_alter_message_chat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
